sd_version: "1.5" # In ['2.1', '2.0', '1.5', 'depth']
input_path: "data/car-turn.mp4" # Accept .mp4, .gif file or a folder with png/jpg sequence
work_dir: "outputs/car-turn"

height: 512
width: 512

inversion:
  prompt: ""

generation:
  control: "pnp"
  control_scale: 1.0
  prompt:
    cartoon: "A jeep car is moving on road, cartoon style."
    # Porsche: "A Porsche car is moving on the beach."

  # VidToMe args. See details in "src/vidtome/patch.py, apply_patch()"
  local_merge_ratio: 0.95
  global_merge_ratio: 0.9
  global_rand: 0.1

  frame_range: [64]

base_config: configs/default.yaml